### ISSUE TITLE
Innerhalb Twitter wird der zweite Link nicht korrekt gesetzt.

### ISSUE THREAD

**Issue by lyckade** [kupferstich/histblogger#12]
Der zweite Link führt zu einem Image not Found
https://ifttt.com/images/no_image_card.png?utm_content=buffer04d26&utm_medium=social&utm_source=twitter.com&utm_campaign=buffer

**Comment by C4z3** [comment]
gestern korrigiert

**Comment by lyckade** [comment]
Dann setz ich mal auf erledigt.
